### PR TITLE
Add support for HTTP/V2PriorKnowledge

### LINKED ISSUE #3163: Insomnia - forcing requests directly to HTTP2 instead of upgrade from HTTP 1.1
Hi, is there any option to force HTTP2 directly without upgrading from HTTP 1.1?  I am talking about an option similar to the curl option --http2-prior-knowledge...

I am running:
Version: Insomnia 2021.1.0
Release date: 3/4/2021
OS: Windows_NT x64 6.1.7601
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1-DEV OpenSSL/1.1.1d zlib/1.2.11 WinIDN libssh2/1.9.0_DEV nghttp2/1.40.0

Thanks!

### PR DESCRIPTION
**Pull request by cgiraldo**
Closes #3163

### CODE REVIEW

**Review by develohpanda — APPROVED** [review]
Thanks for the PR! 🚀

**Comment by develohpanda** [comment]
Hi @cgiraldo! https://github.com/Kong/insomnia/pull/4177 was just merged into develop, which slightly refactors this area of code hence the conflicts. Should be fairly straightforward to resolve, apologies for the conflict!

**Comment by cgiraldo** [comment]
@develohpanda , I resolved the conflict.
KR

**Comment by cgiraldo** [comment]
Sorry, I accidentally removed the `case HttpVersions.V2PriorKnowledge:` when resolving the conflict. 
With the last commit, the tests should now pass.

**Review by jackkav — APPROVED** [review]
🚀

**Pull request merged**
