### PR TITLE
Change default keyboard shortcut to bring up the keyboard settings

### LINKED ISSUE #2018: [Bug] Hotkey to show keyboard shortcuts conflicts with macOS
**Describe the bug**
The default keyboard shortcut to bring up the keyboard settings is `cmd+shift+/`

image

However, macOS has this as a default key binding that brings up the 'help' menu:
image

**To Reproduce**
1. Use `cmd+shift+/` keyboard shortcut
2. Notice the 'help' menu opens instead of the keyboard settings

**Expected behavior**
I'd expect the keyboard settings to pop up. A possible alternative default for this setting would be `cmd+/`.

**Screenshots**
See Above

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103)
 - Installation Method: website download
 - App Version: Version 7.1.1 (7.1.1.3350)

**Additional context**

### PR DESCRIPTION
**Pull request by jgiovaresco**
Moving from `cmd+shift+/` to `cmd+ctrl+shift+/`

Closes #2018

Note: After changing the default keyboard, I needed to reset the binding in the keyboard settings to see the change.

### CODE REVIEW

**Review by develohpanda — APPROVED** [review]
Looks great!

**Comment by SergioSuarezGil** [comment]
**cmd+ctrl+shift+/**  doesn't work on European Keyboard with macos :(

**Comment by develohpanda** [comment]
@SergioSuarezDev you should be able to change the shortcut to anything from Preferences > Keyboard :)

image

**Comment by SergioSuarezGil** [comment]
> @SergioSuarezDev you should be able to change the shortcut to anything from Preferences > Keyboard :)
> 

Hi! Thanks but.. **comment/uncomment** shortcut is not on this keyboard preferences :(

**Comment by develohpanda** [comment]
Ah yes, that one is unfortunately not configurable currently. Could you please open a new feature request for this?

https://github.com/Kong/insomnia/blob/cbc1cfc8b8e86822ec5303ff1f8310e2795c8258/packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx#L78

**Comment by SergioSuarezGil** [comment]
@develohpanda done :) 
https://github.com/Kong/insomnia/discussions/4112

**Pull request merged**
