### PR TITLE
Bump up `httpsnippet` to 1.22.0 for Kotlin and Axios code generation support

### LINKED ISSUE #2516: Kotlin Http Request Code Generation
**Is your feature request related to a problem? Please describe.**
Currently, Insomnia could let us generate Java code. However, I am an Android developer, and I always wanted to generate **Kotlin** code instead of Java code for OkHttp request. Also, Kotlin now becomes one of the most popular languages.

**Describe the solution you'd like**
I have made a [pull request](https://github.com/Kong/httpsnippet/pull/172) to [httpsnippet](https://github.com/Kong/httpsnippet), but got no comments.

**Describe alternatives you've considered**
Even though **Android Studio** could convert Java code into Kotlin code, I think it'd be much nicer to have it. 
There are quite a lot of cool HttpClient for **Kotlin** only such as [fuel](https://github.com/kittinunf/fuel) and [ktor](https://ktor.io/clients/index.html). 

> I'm planning to create those targets as well if my current pull request is merged.

### PR DESCRIPTION
**Pull request by seanghay**
Closes #2516 

`httpsnippet@1.22.0` comes with Kotlin and Axios code generation.

### CODE REVIEW

**Comment by seanghay** [comment]
However, it doesn't highlight Kotlin code. :/
image

**Comment by develohpanda** [comment]
Looks like defining mime type as `text/x-kotlin` should get it working? https://www.libraart.ro/js/CodeMirror/mode/kotlin/index.html

**Comment by seanghay** [comment]
> Looks like defining mime type as `text/x-kotlin` should get it working? [libraart.ro/js/CodeMirror/mode/kotlin/index.html](https://www.libraart.ro/js/CodeMirror/mode/kotlin/index.html)

I really don't know where to add that mine-type to.

**Comment by develohpanda** [comment]
> I really don't know where to add that mine-type to.

No worries - I'm not familiar with this area of code off the top of my head, so when I get a chance to dig into this further I'll chime back 😊

**Comment by develohpanda** [comment]
@seanghay Looks like you just need to add another condition to (the end of) this function. https://github.com/Kong/insomnia/blob/c5d36a5223efe11f71d2a5a8cee0fea546349a4b/packages/insomnia-app/app/ui/components/codemirror/code-editor.js#L702-L719

```diff
...
+   } else if (mimeType.includes('kotlin')) {
+     return 'text/x-kotlin';
+   } else { 
      return mimeType; 
    } 
...
```

For context: all of the code blocks in Insomnia use CodeMirror as the underlying component, as does the generate code modal: `generate-code-modal.js` > `code-editor.js` > `CodeMirror`.

**Comment by seanghay** [comment]
image

It's working now. Thanks @develohpanda !

**Comment by seanghay** [comment]
It's working now! Thanks @develohpanda

**Review by develohpanda — APPROVED** [review]
Nice 🎉 Excited to get this merged!

**Pull request merged**
