### PR TITLE
ca cert support

### PR DESCRIPTION
**Pull request by jackkav**
changelog(Improvements): Added support for setting CA certificates in workspace settings

image

questions
- should we store the file path of the file contents?
  - client certs are paths also, and are shared only on gitsync
- should we store it in the workspace or make a new model?
  - new model is more flexible
- should we support team sync and/or git sync?
  - client certs don't currently support team sync, and git sync with paths does work but doesn't really make sense without support for relative paths and path validation.
- should we combine the root certificate with the ca cert ourselves or just let the user combine them?
  - @joepdegroot / @ErikKringen / @bmarwell any preference?

  
 

Related discussion: #3617
Related issue: #675
Related PR: #3203

Closes: INS-320
Closes: INS-322
Closes: INS-1669

### CODE REVIEW

**Comment by ErikKringen** [comment]
> should we combine the root certificate with the ca cert ourselves or just let the user combine them?

I think it would be most beneficial to take in the CA exactly as given and leave it up to the user to merge as needed.

**Comment by joepdegroot** [comment]
No strong preference on this. Agree with Erik to leave it to the user to merge.

Maybe good to also have a checkbox option to enable/disable the default/system CAs, to prevent the server certificate to be verified by those by accident...?

**Review by filfreire — APPROVED** [review]
LGTM, didn't test, hoping for the best

**Comment by wioxjk** [comment]
Sorry for necroing this - but is it possible to import a custom RootCA globally instead?

**Pull request merged**
