### PR TITLE
Replace time and size with URL in history dropdown (#677)

### LINKED ISSUE #677: [Improvement] Add request url in history preview list
In the history preview list (see screenshot below), it would be great to add the request URL (on hover, now that there's no enough real-estate).

screen shot 2017-12-22 at 2 56 03 pm

I always have to click on a number of items before getting the actual request from history.

Let me know if I need to provide any more information.

-na

### PR DESCRIPTION
**Pull request by iansu**
Closes #677

### CODE REVIEW

**Comment by iansu** [comment]
Thank you. I use Insomnia regularly so happy to contribute. 😀

**Comment by ProfNandaa** [comment]
Thank you for pulling this off @iansu 👏

**Comment by roboslone** [comment]
This actually breaks my workflow, can this behaviour be optional?

**Comment by gschier** [comment]
Hey @roboslone. What's your workflow? I'd be open to making it configurable, but maybe there's a way to modify the new interface to satisfy your workflow.

**Comment by gschier** [comment]
Probably best to discuss this in a new issue so it doesn't get lost. Do you want to create one?

**Comment by roboslone** [comment]
@gschier my workflow is that I use Insomnia to test backend handlers that I'm currently working on. I make changes on backend, send a request, then make some other changes. After several iterations I need response times to determine which changes made it lower. Seeing response times in history is really useful in that case.

**Comment by gschier** [comment]
Thanks for the info. I actually just added those tags back so your workflow should be back to normal in the next release.

image

**Pull request merged**
