### PR TITLE
fix importing creates duplicate resources

### PR DESCRIPTION
**Pull request by huuphat1908**
Current logic
- Always generate new id for resources when importing
- No check for existing resources

New logic
- Only generate new id for resources when importing if the resource has no id
- Add logic to check if resources have already existed

Test data
- [5946-original-config.json](https://github.com/Kong/insomnia/files/14228402/5946-original-config.json)
- [5946-original-config-with-additional-request.json](https://github.com/Kong/insomnia/files/14228400/5946-config-with-additional-request.json)

Test evidence
- Before: https://drive.google.com/file/d/1lxiVQCxYQvzTlecmDBDAGc7BZdLh_xN_/view?usp=sharing
- After: https://drive.google.com/file/d/1VkfwnGxU3CgMJwJrwzc2rVsxz2Dj0kRx/view?usp=sharing

Related issue: https://github.com/Kong/insomnia/issues/5946

### CODE REVIEW

**Comment by TiagoGouvea** [comment]
This fix is highly relevant for us!

**Comment by gatzjames** [comment]
Thanks for the PR!
Closing as this creates other issues on the UX and will be addressed in a separate PR.

**Comment by stevelw** [comment]
> Thanks for the PR! Closing as this creates other issues on the UX and will be addressed in a separate PR.

Where was this addressed? I currently have this issue.

**Comment by hxgdzyuyi** [comment]
> Where was this addressed? I currently have this issue.

Where was this addressed? I currently have this issue.

**Pull request closed without merging**
