### PR TITLE
improvement: the folder deletion

### LINKED ISSUE #6487: [Feature Request] Add warning on delete folder
### Expected Behavior

When I delete a folder, I expect there to be a message advising that all requests will be deleted

### Actual Behavior

I click delete and the folder is deleted without any warning

### Reproduction Steps

1. Right click on folder
2. Click on delete 
Folder deleted

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

_No response_

### Insomnia Version

2023.5.8

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

Downloaded from Insomnia

### Last Known Working Insomnia version

_No response_

### PR DESCRIPTION
**Pull request by kobenguyent**
resolves #6487 

- bring back delete confirmation
- move delete outside for faster access

https://github.com/Kong/insomnia/assets/7845001/3f37fa1b-3c3b-4e44-bdcc-76d56536460e

### CODE REVIEW

**Comment by rwmde** [comment]
Hi @kobenguyent, I'm from https://github.com/Kong/insomnia/issues/6487 too. 
I have a small proposal, if it wouldn't be a big headache for you: add a pop-up window instead of a confirmation button, that appears at the same place where deletetion-button is. You saved user from a single misclick, but haven't saved them from double-click 😅

**Comment by kobenguyent** [comment]
hey @ankoyeeri thanks for your input, per checked with @gatzjames.

```
This one we want to standardise all over the app so we might go with a Confirmation dialog for now since we don't have an accessible confirm button in menus
```

**Comment by sunny-chung** [comment]
How about only counting as "confirmation" if the time difference between two clicks are greater than an interval, say 0.5 seconds? This saves users from an unintended double-click. An animation can be added to make the behaviour doesn't look weird.


https://github.com/Kong/insomnia/assets/14835950/f5562b37-0a7a-4864-8a70-601fbed79bc7

**Comment by gatzjames** [comment]
Closing as this is already implemented

**Pull request closed without merging**
