### PR TITLE
clears npm install (blocking) error by fixing dep. version mismatch

### PR DESCRIPTION
**Pull request by dimitropoulos**
I was in the process of writing some tickets for upgrading our node version and noticed that when we do so we will get a blocking error because of a dependency mismatch between insomnia-components and insomina-app that newer versions of node will not allow:

```console
dimitri@dimitri:~/src/github.com/Kong/insomnia/packages/insomnia-app$ npm install foo
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: insomnia-app@2.3.0
npm ERR! Found: styled-components@4.4.1
npm ERR! node_modules/styled-components
npm ERR!   styled-components@"^4.4.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer styled-components@"^5.1.1" from insomnia-components@2.3.0
npm ERR! node_modules/insomnia-components
npm ERR!   insomnia-components@"2.3.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/dimitri/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dimitri/.npm/_logs/2021-06-30T18_34_02_978Z-debug.log
```

Thankfully, there were ["no breaking changes (TM)"](https://styled-components.com/releases#v5.0.0) to move insomnia-app to styled-components v5, which insomnia-components was already using.

I tested this by checking the rendering of a styled-components component in insomnia-app (in my case, I picked HelpTooltip since it's easy to find in the preferences).

### CODE REVIEW

**Comment by dimitropoulos** [comment]
```
insomnia-app:     Error: Uncaught [Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
insomnia-app:     1. You might have mismatching versions of React and the renderer (such as React DOM)
insomnia-app:     2. You might be breaking the Rules of Hooks
insomnia-app:     3. You might have more than one copy of React in the same app
```

Wow, it _STRIKES AGAIN_.  Funny to see that happen twice in the same day with completely different PRs with completely different goals.

@develohpanda it'd be cool to hear what you think on this.  I'll pull into draft for now (since, this isn't a very high priority).

**Comment by jackkav** [comment]
I saw this when spiking babel-preset-typescript for components https://github.com/jackkav/insomnia/commit/d68d3846b464c909123ddfd0c14d317c246979b5

**Comment by develohpanda** [comment]
Wow this is such an old PR, I totally missed it, let me know if it's still an issue and I'll dig into it

**Comment by jackkav** [comment]
I suspect it will happen if you rebuild the package lock for the `insomnia-components` package. In my case I linked to the diff above that triggered it for me (installing a package).
Still an issue.

**Comment by develohpanda** [comment]
There's some magic we had to pull with webpack aliases to allow for `insomnia-components` usage by plugins using a different version of React. If it's related to that chances are I can help, and can explain why it's built the way it is right now.

**Comment by dimitropoulos** [comment]
to be honest, this was long enough ago + I spent so little time on it that I really don't remember anything significant about it other than that I read the styled-components changelog very closely.  lemme know when this comes up, whenever we hit it, I guess, and we can revisit.

**Comment by develohpanda** [comment]
@dimitropoulos can we close this PR in that case?

**Comment by jackkav** [comment]
I rebuilt the package json in #4309 and didn't see the styled-components issue I mentioned above, its likely because I transpiled with babel instead of tsc.

**Comment by dimitropoulos** [comment]
fixed by https://github.com/Kong/insomnia/pull/4558

**Pull request closed without merging**
