### PR TITLE
doc(code-snippets): update link to use Kong org

### PR DESCRIPTION
**Pull request by darrenjennings**

### CODE REVIEW

**Review by reynolek — APPROVED** [review]
Thanks Darren!

**Review by dimitropoulos — APPROVED** [review]
:heart: nice to see yah @darrenjennings 

(I checked and there appear to be no other mentions of `mashape` in the repo)

**Comment by dimitropoulos** [comment]
(rebased it and resolved the conflict) thanks for basing it on a commit from _LAST NOVEMBER_ **_DARRRREEENNNN_** (haha jkjk)

**Review by develohpanda — APPROVED** [review]
More on the way I am _sure_ 😉 nice to see you!!

image

**Pull request merged**
