### PR TITLE
Add 'Cookie' attribute to `{% response %}` template tag

### LINKED ISSUE #5802: Add "Response -> Cookie" template tag
The `{% response %}` template tag currently allows us to chain requests and use some attributes from the previous request as templated values. Great! Unfortunately, the cookies of the chained request are not available. 

I've got some APIs I need to access which requires you to use a previously fetched cookie as a Bearer Token, so adding this would be very useful.

(I've got some code ready for it in: https://github.com/Kong/insomnia/compare/develop...strokirk:insomnia:response-cookie-attribute?expand=1)

### PR DESCRIPTION
**Pull request by strokirk**
This allow the user to pick the value of a specific cookie from a previous request, using request chaining to automatically re-send the request when it becomes stale.

Useful for certain APIs which for example requires a bearer token that is returned as a cookie.

Closes #5802

### CODE REVIEW

**Comment by strokirk** [comment]
@filfreire anything I can do to help push this PR along?

**Comment by strokirk** [comment]
@filfreire @mheap Hi again! Anything I can do to help in reviewing and merging this PR?

**Comment by grigorii-horos** [comment]
@filfreire @mheap Can you merge this feature? 

@strokirk Thanks for PR!

**Comment by gatzjames** [comment]
Closing as this can use the `Response Header` and then `Set-Cookie` attribute instead.

**Pull request closed without merging**
