### PR TITLE
[#5400] Fix data-url encode parser

### LINKED ISSUE #5400: Insomnia does not parse curl request correctly
### Expected Behavior

The form name and value should be seperated:

image

### Actual Behavior

Both the form name and value are in the same place:

image

### Reproduction Steps

- Create new request
- Paste below curl command into request url box:

  ```text
  curl --request POST https://login.microsoftonline.com/domain.onmicrosoft.com/oauth2/v2.0/token --header "Content-Type: application/x-www-form-urlencoded" --data-urlencode "client_id=9154f684-a955-44a3-b577-8f9134502248" --data-urlencode "scope=https://graph.microsoft.com/.default" --data-urlencode "client_secret=804237f3-1c05-44aa-8bd3-4e38a90fdbf6" --data-urlencode "grant_type=client_credentials"
   ```

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

_No response_

### Insomnia Version

2022.7.0-beta.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro Version 21H2

### Installation method

Download from github release

### Last Known Working Insomnia version

_No response_

### PR DESCRIPTION
**Pull request by tuyen-at-work**
This PR closes #5400

### CODE REVIEW

**Comment by tuyen-at-work** [comment]
Hi @filfreire @jackkav @gatzjames could you allow running workflows on this PR, please!

**Comment by marckong** [comment]
@tuyen-at-work Hi Tuyen, it seems we cannot push commit to your remote branch, so we can't really collaborate on this PR with you. If you allow, we can rebase this and push some modifications and run the workflows perhaps.

**Comment by marckong** [comment]
For the future reference, we may recommend you to rebase instead of merging the latest develop into the PR branch.

**Comment by tuyen-at-work** [comment]
Hi @marckong yes feel free do do it, I'm happy if you can improve the changes

**Comment by tuyen-at-work** [comment]
Hi @marckong I rebased the PR and add tests/fix lints. I cannot find any place where I can enable insomnia maintainers to edit my forked branch. Maybe the option only available creating new PR, not when update existing one. I still happy if you rebase it yourself and update if you find anything can be improved.

**Comment by tuyen-at-work** [comment]
Close this PR and create #5409 intead, enable editing from collaborators.

**Pull request closed without merging**
