### PR TITLE
sync: fix the broken history snapshot "restore" functionality

### LINKED ISSUE #6232: Insomnia Sync - Branch History "Restore" Broken on Collections
### Expected Behavior

When using Insomnia Sync with a Collection (_not git sync, not a "Document"_), click the "Restore" button on a previous snapshot on a branch history should ["[...] revert the workspace to that state stored in the snapshot"](https://github.com/Kong/insomnia/blob/b9c709695806221c502e3bf8a26c1fc0c904508e/packages/insomnia/src/ui/components/modals/sync-history-modal.tsx#L60).

### Actual Behavior

You can click the button (and the subsequent "confirm" and "done" buttons that appear in its place) but nothing happens except an error is logged to console, the state remains the same:
image

### Reproduction Steps

On the Official app for Mac
1. Download the application for macOS (or build it for macOS with `npm run app-package`
2. Create a new Collection
3. Add a new folder to it
6. Add a request to the new folder
4. Take a snapshot
5. Add another folder
6. Add a request to the new folder
7. Take a snapshot
8. Open the branch "History"
9. Click "Restore" on a previous snapshot
10. See that nothing changes

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

## Reproducing Locally:

To reproduce while running the app locally I ran:
1. `npm boostrap`
2. `npm app-package`
3. Install with the dmg output into `dist`
4. Run the app, follow the repro steps detailed above

I also found the issue...

## The Bug:

https://github.com/Kong/insomnia/blob/b9c709695806221c502e3bf8a26c1fc0c904508e/packages/insomnia/src/ui/components/modals/sync-history-modal.tsx#L97-L99

This `// @ts-expect-error -- TSCONVERSION` comment was presumably added because without it the TS linter will throw an error about the type of the `delta` var arg, e.g.:
```
TS2345: Argument of type '{ upsert: (Record<string, any> | null)[]; remove: StatusCandidate[]; }' is not assignable to parameter of type 'Operation'.   Types of property 'upsert' are incompatible.     Type '(Record<string, any> | null)[]' is not assignable to type 'BaseModel[]'.       Type 'Record<string, any> | null' is not assignable to type 'BaseModel'.         Type 'null' is not assignable to type 'BaseModel'.
```

However, this also hides the fact that `db` was never imported:
https://github.com/Kong/insomnia/blob/b9c709695806221c502e3bf8a26c1fc0c904508e/packages/insomnia/src/ui/components/modals/sync-history-modal.tsx#L1-L21

## The Fix:

The following steps fixed this issue for me locally:
1. Import the `db` just like everywhere else it's used
    ```typescript
    import { database as db } from '../../../common/database';
    ```
2. Remove the ts-ignore comment from above the line:
    ```
    await db.batchModifyDocs(delta);
    ```
5. Now alter that line to something that works (however you want but I just converted to `any`)
    ```
    await db.batchModifyDocs(delta as any);
    ```

### Insomnia Version

2023.4.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.5

### Installation method

https://insomnia.rest/download

### Last Known Working Insomnia version

_No response_

### PR DESCRIPTION
**Pull request by DannyHinshaw**
sync: fix the broken history snapshot "restore" functionality by importing db.

Closes #6232

### CODE REVIEW

**Review by jackkav — APPROVED** [review]

**Comment by jackkav** [comment]
Thanks @DannyHinshaw for the catch, will get this in right away!

**Comment by DannyHinshaw** [comment]
Thanks @jackkav ! Any chance we could get a patch release with this for the latest distributed version 2023.4.0? This has been a big source of pain for our companies migration to using this tool from PAW/RapidAPI, so getting this out would help _a lot_ 🙏

**Comment by jackkav** [comment]
I made a beta.10 right after merging https://github.com/Kong/insomnia/releases/tag/core%402023.5.0-beta.10

**Comment by chrsm** [comment]
@jackkav what is the process (or plan) for cutting an actual release? We'd like to use this in the released version rather than beta.

**Comment by jackkav** [comment]
We're planning to get 2023.5.0 release out in the next few days, just completed a major refactor (removed 40k lines of cruft, and a bunch of outdated dependencies) so its been a bit hairy getting everything stable. Thanks for your patience.

**Pull request merged**
