### PR TITLE
distinguish upstreams name in declarative config

### PR DESCRIPTION
**Pull request by jackkav**
Closes INS-894

upstreams node name matched services node name confusingly, this change adds .upstream to it for clarification.

**Before:**
```
upstreams:
  - name: CAS
```
**After:**
```
upstreams:
  - name: CAS.upstream
```
image

### CODE REVIEW

**Review by develohpanda — CHANGES_REQUESTED** [review]
I think one item wasn't totally clear in the ticket, and that is the upstream name is also referred to in the `service.host` property. Therefore, whatever upstream name is generated, the `service.host` property needs to be the same.

<details>
<summary>Input</summary>

```yaml
openapi: '3.0.2'
info:
  title: Sample Spec
  version: '1.2'
servers:
  - url: https://200.insomnia.rest
tags:
  - name: Folder
paths:
  /global:
    get:
      tags:
        - Folder
      responses:
        '200':
          description: OKs
  /override:
    get:
      responses:
        '200':
          description: OK
```

</details>

<details>
<summary>Output</summary>

```diff
_format_version: "1.1"
services:
  - name: Sample_Spec
    protocol: https
-   host: Sample_Spec
+   host: Sample_Spec.upstream
    port: 443
    path: /
    plugins: []
    routes:
      - tags:
          - OAS3_import
        name: Sample_Spec-global-get
        methods:
          - GET
        paths:
          - /global$
        strip_path: false
      - tags:
          - OAS3_import
        name: Sample_Spec-override-get
        methods:
          - GET
        paths:
          - /override$
        strip_path: false
    tags:
      - OAS3_import
upstreams:
- - name: Sample_Spec
+ - name: Sample_Spec.upstream
    targets:
      - target: 200.insomnia.rest:443
        tags:
          - OAS3_import
    tags:
      - OAS3_import

```

</details>

**Comment by jackkav** [comment]
Thanks @develohpanda

**Review by Tieske — APPROVED** [review]
lgtm 🎉

**Review by dimitropoulos — APPROVED** [review]
lgtm: I also looked around and verified that there's not a competing problem over on the kubernetes side.

**Review by develohpanda — APPROVED** [review]

**Pull request merged**
