### PR TITLE
fix #5942: Retain exported ID for resource

### LINKED ISSUE #5942: version 2023.2 Imports of request collection no longer work
### Expected Behavior

import a file exported from insomnia as insomnia json v 4 containning request directory with three commands one of which has a tag
[Insomnia_2023-05-04.txt](https://github.com/Kong/insomnia/files/11394913/Insomnia_2023-05-04.txt)

expected bahavior is creation of request direcotry
with the command and tag intact

### Actual Behavior

upon importing whis file into insomnia v2023.2. a document is created instead name 'Untitled'
image
and the Tag becomes disconected
image

also if insomnia already contains the apropriatly named  request directory import will create duplicate requests.
i think that both tag will point to same request.

### Reproduction Steps

1. export request directory with a tag
2.  import into insomnia
3. request get duplicated
4. delete the request directory
5. import into insomnia
6. Unnamed Document is created and tag is broken 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

_No response_

### Insomnia Version

2023.2.

### What operating system are you using?

Windows

### Operating System Version

Edition	Windows 10 Pro Version	22H2 Installed on	‎06/‎02/‎2023 OS build	19045.2846 Experience	Windows Feature Experience Pack 120.2212.4190.0

### Installation method

insomnia updated

### Last Known Working Insomnia version

i think the previous version was fine but dont have the nuber on hand since the update

### PR DESCRIPTION
**Pull request by adammkelly**
Closes https://github.com/Kong/insomnia/issues/5942

If an imported config has references to requests via the response plugin they are dereferenced as the imported config gets all new ids.

If this has downstream consequences, please let me know.

changelog(Fixes): Added a fix to retain the id from imported resources

### CODE REVIEW

**Review by mehr-licht — APPROVED** [review]

**Comment by wingedrhino** [comment]
It would be nice if this MR is prioritized! Export of request chains has been pretty broken for a while now.

**Review by gustoliv — APPROVED** [review]

**Comment by dukesteen** [comment]
When is this being released? seems like a simple fix to me

**Review by gustoliv — APPROVED** [review]

**Review by Yocker95k — APPROVED** [review]

**Comment by pjloomis** [comment]
My team is experiencing the same problem.  If you export a document, then import later, existing requests are assigned new request IDs.  Every Tag, Request Chaining, basically everywhere you've made a reference to a request's ID is now broken.  

Steps to reproduce:
1. Create a new design document
2. Add a Get request.  Here's a public api - https://datausa.io/api/data?drilldowns=Nation&measures=Population
3. Open settings for the Request and save the request id (req_00534c74137948da90521431b379b27b)
4. Export the design document
5. Delete the design document
6. Import the design document
7. Open and go to the request
8. Open settings for the request and note that the request ID has changed (req_2d5680a437594dc6986d75f9dfda6988)

This occurs for Insomnia 8.4.0 on both PC and Mac

**Comment by jnazaren** [comment]
Bump - any updates on when this might be released?

**Comment by dukesteen** [comment]
> Bump - any updates on when this might be released?

I just switched to postman again..

**Review by jnazaren — APPROVED** [review]

**Comment by jnazaren** [comment]
@gatzjames @filfreire

**Comment by PedroLuisBrilhadori** [comment]
By debugging a little, you can see that each request has a unique and global id. Wouldn't it be better for each request to be unique in its document?

With these corrections, it is possible to import requests with their ID'S, however. If you already have these ID'S in your insomina it returns an error. 

I'm trying to research more about requests and documents within the code.

**Comment by kap199297** [comment]
Is there any update on this PR? When it is going to be available?

**Comment by tl-luca-mazzanti** [comment]
Is this going to be deployed?

**Review by PedroLuisBrilhadori — APPROVED** [review]

**Comment by gatzjames** [comment]
Closing as this creates other issues and will be addressed in another PR

**Pull request closed without merging**
