### PR TITLE
Implemented Prettier for GraphQL formatting

### LINKED ISSUE #3242: [umbrealla] use a true graphql prettifier (i.e., one designed for prettifying)
**Describe the bug**
There are a number of bugs that arise from our current approach to prettifying graphql:
- comments are destroyed https://github.com/Kong/insomnia/issues/1124
- indentation is not respected https://github.com/Kong/insomnia/issues/2301
- very long query parameters (which is not terribly uncommon) don't wrap https://github.com/Kong/insomnia/issues/2600
- (and probably more that I haven't yet found - let me know if so).

**To Reproduce**
1. Create a GraphQL request
2. click `Pretify GraphQL` and observe the results

**Expected behavior**
The above issues have different solutions, but the over-arching concept is that the prettifying should work as one might naturally expect (and definitely without destroying information).

I think we should look at other tools and graphql clients to see how they approach this problem and go with the most widely adopted solution.  I believe prettier may be an option, but the docs are down at the time of writing this issue.

### PR DESCRIPTION
**Pull request by ariasmn**
Implementing a specific library for GraphQL formatting was needed to close some issues.
This should close #3242 , which links to three other issues related to GraphQL formatting.

### CODE REVIEW

**Review by dimitropoulos — APPROVED** [review]
fantastic!

I tested with 

```graphql
type Query {
  me: User
}

# comment that shouldn't go away
type User {
  id: ID
  name: String
}

mutation UpdateBasicInfo($id: ID!, $firstName: String, $middleName: String, $lastName: String, $gender: string, $birthDate: DateTime) {
  updateEmployee(employee: {id: $id, firstName: $firstName, middleName: $middleName, lastName: $lastName, gender: $gender, birthDate: $birthDate }) {
    id
    firstName
    middleName
    lastName
    gender
    birthDate
  }
}
```
| BEFORE | AFTER |
| - | - |
| Screenshot_20210923_123642 | Screenshot_20210923_123524 |

So, comments are not removed, indent is respected (including tabs or not), and long lines wrap like you'd expect.

This is great.  Thanks!!

**Comment by wdawson** [comment]
Thanks for the PR @ariasmn ! Looking forward to getting this out to everyone 🚀

**Comment by ariasmn** [comment]
@dimitropoulos @wdawson Thank you so much for the feedback and the fantastic job you do! Glad that I could help :smile:

**Review by gatzjames — APPROVED** [review]
🚀 LGTM! Works great!

**Pull request merged**
