### PR TITLE
feat(Environment Picker): Simplify the UI

### PR DESCRIPTION
**Pull request by gatzjames**
Highlights:

- [x] Collection and Global environments are on the same column
- [x] There is a new column that displays the active environments in the hierarchy they are applied

image

### CODE REVIEW

**Review by jackkav — DISMISSED** [review]

**Review by jackkav — APPROVED** [review]

**Comment by AlbinBackstom** [comment]
Is there any way to display the current set environment as it was before? Now it only displays the </> Manage Environments button and its impossible to know what environment you are using without opening the new menu. 
image

**Comment by jonataswalker** [comment]
Please revert this not helpful change.

**Comment by fadelchaidarf** [comment]
Now I have to be extra careful just in case I hit the production environment. Before, I know what environment I'm in just by a glance, the environment color was super nice too

**Comment by JoakoV3** [comment]
Can we add this fix? It was super nice to see the color of the environment you are working on #7607

**Comment by AlbinBackstom** [comment]
Thanks for fixing it!

**Pull request merged**
