### PR TITLE
fix: improve sending request performance [INS-3280, INS-3256]

### PR DESCRIPTION
**Pull request by ihexxa**
Changes:
This change improves performance for following use cases by 50%:
  - REST requests are chained
  - One request depends on many environments
And it also fixes prompting twice in rendering.

### CODE REVIEW

**Comment by filfreire** [comment]
@ihexxa I tested this locally in 2 of the cases you mentioned:
- multiple environment variables referring to one value, in my case a response body attribute
- a single request that used those environment variables

and I haven't noticed any performance improvement.

Can you share the steps you took to test this where the performance improvement is better observed?

**Review by filfreire — COMMENTED** [review]
@ihexxa I tried using the performance collection you shared, but on Import seems like it's touching an existing bug where the request id in the chained requests no longer apply, causing errors like `Could not find request req_<id>`

image

But this is unrelated to this PR, gonna add a note for it internally.


As for the performance, I've tried with a collection of my own, similar to the one you shared. I've found some things which we might need to tackle in this or upcoming PRs.

1) At a certain number of variables, everytime we resend the request, the template tags re-render and the slower the cpu the more time they are left in a state like the one in these screenshots
Screenshot 2023-11-10 at 11 02 52
Screenshot 2023-11-10 at 11 05 25



2) I think we have an edge-case where if the request chains to "itself" then regardless of the performance optimization in this PR or not, the request take 1 minute or more to render


3) I've noticed that the response rendering is a bit faster in this PR. 

4) I noticed several times a performance improvement, both opening a collection and then switching to a request that has a lot of template tags - not sure if this is even to be expected with these changes

5) there's a period of time between the response "loading" and then it being rendered where the UI is frozen, and the loading spinner timer shows the same value - this happens for both this PR branch as well as latest `develop`

From my side I think LGTM, but I would recommend @jackkav and @gatzjames also review this.

**Comment by ihexxa** [comment]
@filfreire Yes, these should be also tackled in the next step, probably in a more comprehensive way.

**Comment by ihexxa** [comment]
I removed the cache part as it is mainly for a specific case.

**Comment by jackkav** [comment]
Reminder: test broken tag in header to see if error modal appears, or what happens

**Comment by ihexxa** [comment]
@jackkav this is true👍 , I've updated the action handler and make it be able to handle error and return it. 

And here are 2 recordings, you can find that main difference is the period before "loading":
https://github.com/Kong/insomnia/assets/24986718/733b1a06-20b7-46f7-adca-004819c96a88
https://github.com/Kong/insomnia/assets/24986718/c9d12160-49e5-4412-9d3c-7af9b96a574c

It also fixes prompting twice.

**Review by filfreire — APPROVED** [review]

**Pull request merged**
