### PR TITLE
Modify threshold to 2MB

### LINKED ISSUE #3115: Configure threshold for "Response over 5MB hidden for performance reasons" message
Hello,

Found this old issue #412 that mentioned displaying large JSON data, linked to this commit c4933badba54fb149923d43c8e927c305d4dcce3 limiting displaying data larger than 5MB i.e. when you see this message: "Response over 5MB hidden for performance reasons".

However, for performance testing, I'd like to lower this threshold?

Is it possible?

### PR DESCRIPTION
**Pull request by Warkanlock**
This issue is related to #3115 in order to low down a little bit the performance threshold use in Insomia UI to **2MB**

Resolves #3115

### CODE REVIEW

**Comment by dimitropoulos** [comment]
posting agreement with https://github.com/Kong/insomnia/issues/3115#issuecomment-802726762

The solution seems to me not to be to [change it to another value](https://www.explainxkcd.com/wiki/index.php/1172:_Workflow) but rather to make it configurable.

**Comment by Warkanlock** [comment]
Yes, I thought it was change it to another value. Now it's seems more reasonable to do it. 

What are your thoughts on this @dimitropoulos? Can we include it as a preference option? Do we want to have a .dot file?

**Comment by dimitropoulos** [comment]
@Warkanlock definitely would want it to be a preference option (and not a dotfile).

**Comment by jackkav** [comment]
Closed as stale.

**Pull request closed without merging**
