### PR TITLE
Replace the KeyboardBinder with hooks

### LINKED ISSUE #4766: Request URL removed when request is duplicated (via keyboard shortcut)
### Expected Behavior

I have created a request that is working fine and now I want to try something different with it, instead of modifying this one I duplicate it and modify the duplicate one with whatever other use case I want to target.
Both the original and the copy should work as expected.

### Actual Behavior

The copy works just like the original did, it's exactly the same as expected. But the original request has now lost the URL, as in the url field is now empty. So I now have to go to the duplicate and copy the url and past it in the original.

### Reproduction Steps

1. Create a request with the usual stuff, url, some headers, perhaps a body if necessary, etc
2. Duplicate the above request
3. Observe the duplicate contains all the fields from the original
4. Inspect the original request and notice it's missing it's url

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Duplicate used to work just fine, it's a regression introduced a few weeks ago.

### Insomnia Version

2022.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.3.1

### Installation method

Download from insomnia.rest

### Last Known Working Insomnia version

Unsure

### PR DESCRIPTION
**Pull request by gatzjames**
This aims to fix many issues with the keydown bindings in the app.

Decision: user defined app hotkeys will always override code editor hotkeys, except showAutocomplete, eg. Cmd+d will duplicate request always never delete line
autocomplete is specific to code editor
If someone wants to use a code mirror hotkey they can rebind our default hotkey

There is now a more explicit way to register keyboard shortcuts and define the elements they will be attached to.
Why the createKeyboardHandler method?
- Handles cases where we check if e.g. `keyCode === 'Enter'` but we incorrectly also handle 'Cmd+Enter'/'Ctrl+Enter' etc.

Class Components that would make the transition easier if they were Functions instead:
- [x] modal.tsx
- [x] graphql-editor.tsx
- [x] graphql-explorer.tsx
- [x] request-switcher-modal.tsx
- [x] app.tsx

In scope
- [x] dropdown toggles
- [x] dropdown closes on esc
- [x] modal closes on esc
- [x] gql editor fetches introspection query with axios
- [x] send and focus request types
- [x] adds tinykey library in order to improve readablility of binding logic
- [x] fixes initialValue typing issue
- [x] types screaming snake case hotkey names
- [x] codeMirror ignores use defined hotkeys
- [x] simplifed modal.tsx to prepare for conditional rendering approach
- [x] special cases enter and esc in a few components
- [x] eliminates the tree walking in modal.tsx
- [x] add key combo modal fc
- [x] simplify hotkeyDefs object and type KeyboardShortcut
- [x] remove the close modal and close dropdown bindings

Out of scope
- examples of a useKeyboardShortcut bound to a specific dom element rather than document.body
- conditionally rendered modals
- decouple import export features from redux

Also closes

Closes #4766
Closes INS-1573
Closes INS-1187

changelog(Fixes): Fixed a number of issues regarding hotkey shortcuts by replacing the KeydownBinder with hooks

### CODE REVIEW

**Comment by daniel-stoneuk** [comment]
I have just been looking into a bug which occurs when you use a keyboard shortcut while a dropdown is open on the `develop` branch.

Screenshot 2022-07-25 at 20 33 10

These lines appear to prevent keyboard shortcuts while a dropdown is open, though they are in an event handler that is called after the `KeydownBinder` in `app.tsx` so fail to do so.

https://github.com/Kong/insomnia/blob/8202b2e59fe957c394d56d0b3ab203d6df49d1b3/packages/insomnia/src/ui/components/base/dropdown/dropdown.tsx#L194-L195

I found this PR and I wanted to mention this behaviour here in case some sort of `zIndex`-style priority should be built into this hook to allow components to stop event propagation. It is reproducible in gatzjames:fix/keybindings-hook.

If this is out of the scope of this PR, I can create an issue and tackle it once this has landed!

**Comment by gatzjames** [comment]
@daniel-stoneuk thanks a lot for mentioning this. It's definitely in the scope and has to do with global shortcuts listening to keyboard events in the body or using the capture phase.

The purpose of this PR is to remove the keyboard binder and make it simpler to reason about keyboard events in the app.

In order to simplify the changes we decided to move as much of the affected components to function components first (remaining list on the pr comment).

Can't promise anything but the plan is to get this merged before the next release 😄

**Review by gatzjames — COMMENTED** [review]
🚀 Just went through a code review and tested most of the affected flows

**Review by jackkav — APPROVED** [review]
We had to break a lot of big rocks in one go in this PR to simplify an approach to keyboard shortcuts that was less indirect. Tested and working fine though.

**Review by marckong — APPROVED** [review]

**Review by filfreire — APPROVED** [review]

**Pull request merged**
