### PR TITLE
feat: add common modal(use react-aria-components)

### PR DESCRIPTION
**Pull request by CurryYangxx**
Added a common modal that build by react-aria-component. In the future,if you need modal, you can use this modal instead of base/modal

### CODE REVIEW

**Comment by jackkav** [comment]
BaseModal and CommonModal appear to be different names for the same thing. If we are creating a second base modal, then please include in the PR description your rationale for what your need it for and introduce your plan to replace the BaseModal if you think it would be better or a reason why both should exist.

**Comment by jackkav** [comment]
use the modal in two places to justify it here.

**Comment by CurryYangxx** [comment]
This is a draft PR，we will discuss it‘s necessity later

**Comment by gatzjames** [comment]
Closing as we haven't used this. Feel free to reopen in case we want it in the future

**Pull request closed without merging**
