### PR TITLE
[Feature] Certificate Authority Settings

### PR DESCRIPTION
**Pull request by coolhome**
Related Issues: #675 and #1432
Status: In Progress

### [Completed] Allow Windows users to pull certificate authorities from the Windows Cert Store
With the help of the library [`win-ca`](https://github.com/ukoloff/win-ca) we are able to pull windows trusted certificates under the users profile. This package can be installed for all operating systems but will only do something on windows.

### Allow Windows/Linux/(Mac?) to provide custom ca bundle
Completed for windows/linux.

Upon research on [CURLOPT_CAINFO](https://curl.haxx.se/libcurl/c/CURLOPT_CAINFO.html) we should be able to allow mac users to also provide a CA file. 

> If the option is not set, then curl will use the certificates in the system and user Keychain to verify the peer.

### Unit Tests
The whole thing needs unit tests still.

### Polish Code
Maybe move the logic outside of network.js into its own file. Maybe a function to return the file that should be used with curl?

## Ideas
* Combine CA bundles?
* Workspace CA files? Would only work with a user provided cert?
* When on Windows use Cert Store, when on Mac use Keychain, else use provided ca info. To overwrite you would add to workspace?

@gschier would love your feedback :)

### CODE REVIEW

**Review by gschier — COMMENTED** [review]
I like what you have here so far! Do you think it's worth splitting this PR into two separate ones? One for the setting to allow Windows (and no one else) users to use the OS bundle and one to let users specify their own bundle?

And yes, `CURLOPT_CAINFO` should work for specifying your own bundle since we're [already using it](https://github.com/getinsomnia/insomnia/blob/36059c848080a60b9d90683c0932a743866677f7/packages/insomnia-app/app/network/network.js#L362) to specify the Linux/Windows one.

**Comment by coolhome** [comment]
@gschier I was thinking that as well. I will resubmit a PR with the ability to use a custom bundle. Later in another PR I will look into implementing the ability to take the OS specific versions.

**Comment by gschier** [comment]
Awesome, that sounds good.

**Comment by develohpanda** [comment]
Hi @coolhome! Thanks a bunch for doing this, awesome work! 💯

I've picked it up to get it across the line after some internal discussions. I have created a PR (#2020) with some refactoring and resolved merge conflicts, so I will close this PR from your fork for now. _Please reopen if you have changes in addition to those here_, and we can take it from there. 😄

**Pull request closed without merging**
