### PR TITLE
fixes #2552:addded a (slightly) more verbose output in check-version.js

### LINKED ISSUE #2552: Improve the output of the node version check script
image

Currently the response at the top is overpowered by the npm error lines. It would be nice to increase the visibility of the output through console log text colors: https://stackoverflow.com/a/41407246.

Note we cannot use an npm module like chalk for this, as the script runs and errors _before_ node_modules are installed.

### PR DESCRIPTION
**Pull request by yashshah1**
* updated version script to show more verbose errors in case of a mismatch node version

Closes #2552

### CODE REVIEW

**Review by develohpanda — COMMENTED** [review]
Nicely done! Could you also please add a screenshot showing what the new output looks like?

**Comment by yashshah1** [comment]
Hey, here you go!

image

**Comment by develohpanda** [comment]
Awesome! Nicely done with adding a link to nvm👌

Two minor points:
- in the case a user does have the correct version installed, we don't want to print anything. So I suggest changing the opening line to something like "Error - incorrect Node version installed!" when a mismatched version is found. Colour this as you see fit!
- the closing line still seems to blend in, and arguably it is the most important - could we please change that to a yellow, for example? Any colour will do to really make it stand out. 😊

**Comment by yashshah1** [comment]
Hey, hope this is a little better!


image

**Review by develohpanda — APPROVED** [review]
Looking really good now, thanks for working on this @yashshah1 🎉 And congrats on your first PR into Insomnia! 😄

**Pull request merged**
