### PR TITLE
Add GrpcRequest and ProtoFile as accepted models for git sync

### PR DESCRIPTION
**Pull request by develohpanda**
image

### CODE REVIEW

**Review by DMarby — APPROVED** [review]
Looks good overall, worked well when I tried it!

One small thing found while testing is that it's displaying the wrong type in the UI, in that it's showing Request instead of gRPC Request.

I believe this is due to the code below, since we're matching on the path, `.insomnia/GrpcRequest/<foobar>.yaml` will match on the Request type model before getting to GrpcRequest:

https://github.com/Kong/insomnia/blob/ec8f72c09b3637c09f9584ee182bb379f6397351/packages/insomnia-app/app/ui/components/modals/git-staging-modal.js#L213-L218

**Comment by develohpanda** [comment]
Oh I completely missed that in the screenshot... Nice catch and notes. I'll fix this before merging.

**Review by DMarby — APPROVED** [review]
:shipit:

**Comment by develohpanda** [comment]
Rebased onto the release branch for 2020.5

**Pull request merged**
