### PR TITLE
[INS-1821] - import/export websocket requests

### PR DESCRIPTION
**Pull request by jackkav**
highlights
- can import
- can export
- unblocks #5123

### CODE REVIEW

**Comment by marckong** [comment]
How to test this change:
1. navigate to the workspace dropdown
image
2. click "Import/Export" dropdown item button
3. click "Export Data" button
4. select the document
5. verify there is websocket request row
image
6. verify the exported json content by each format (json, yaml, har)

**Comment by marckong** [comment]
I just ran the local smoke test with this branch. I verified the export result in json and yaml, but for har, I see this:
image. Is this an expected result?

**Comment by jackkav** [comment]
> . Is this an expected result?

Yes this is expected, it would be an export of the responses, in normal conditions.
Its too early to make a decision about exporting websocket responses since 
- we haven't decided if they should diverge
- it touches the nunjucks rendering code path
- grpc does exactly the same thing
So let's scope this one out. I'll make a ticket in triage. INS-1847

**Review by gatzjames — APPROVED** [review]
🚀

**Pull request merged**
