### PR TITLE
[Re-Submitted] Added support for file extension filtering as well as ability to select a directory to file picker dialog

### PR DESCRIPTION
**Pull request by nickhomme**
I've added support for the file input to have a file type filter applied as well as the ability to select directories if allowed.

Reasoning for this is to provide plugins the ability to have more complex capabilities such as looping through files in a directory or only allowing certain files to be selected.

Possible improvements would be to also allow option of multiple files to be selected.

### CODE REVIEW

**Comment by nickhomme** [comment]
Looks like my IDE performed some auto-formatting. Let me know if you'd like me to revert those formatting changes.

**Comment by gschier** [comment]
Thanks for the PR @nickhomme! Since it's such a small PR, the formatting stuff is fine. It's easy enough to find the meaningful code changes 😄 👍

**Comment by nickhomme** [comment]
@gschier 
Is there something additional I need to do for the third check to run?

**Comment by gschier** [comment]
It's okay. Sometimes that last one doesn't run for some reason. Also, I haven't forgotten about this. Going to get it into the next release for sure!

**Pull request merged**
