### PR TITLE
oAuth 1.0a Support

### LINKED ISSUE #197: [Feature] OAuth 1.0 Authentication
Insomnia currently supports OAuth 2.0 but not 1.0. AFAIK the 1.0 spec is more complicated to implement, but I haven't done enough research yet. 

If anyone knows OAuth 1.0 well (or wants to learn) and would like to start work on this, that would be amazing! Also, **please 👍 this if you want this feature**.

### PR DESCRIPTION
**Pull request by besolov**
Closes #197 

It's a basic support for oAuth 1.0a authentication. [oauth-1.0a](https://www.npmjs.com/package/oauth-1.0a) library is used for authentication support. At this moment only HMAC-SHA1 and PLAINTEXT signature methods are supported.

### CODE REVIEW

**Comment by gschier** [comment]
Thanks for doing this! Will take a closer look this week. 

One thing I noticed before I start the actual review. There is no need for the external crypto package right? Node has it built in now.

**Comment by gschier** [comment]
https://www.npmjs.com/package/crypto

**Comment by besolov** [comment]
@gschier Yeah, it was from example for oauth-1.0a library. It is used for create signature. I'll dig it tomorrow, for replacement with built-in Node module.

**Comment by besolov** [comment]
@gschier Oh, it was easy, I've removed 'crypto' from dependencies and it still works :)

**Comment by gschier** [comment]
Could have been an old example. Thanks for the quick update 😀

**Comment by besolov** [comment]
Here it is:
screen shot 2017-11-06 at 21 22 33

**Comment by gschier** [comment]
Nice! Excellent work @besolov 😄

**Pull request merged**
