### PR TITLE
Fix CI Intermittent failures

### PR DESCRIPTION
**Pull request by dimitropoulos**
closes: INS-694

### CODE REVIEW

**Comment by dimitropoulos** [comment]
@develohpanda I think we may also need to specify peerDependencies correctly according to:

> Specify any peerDependencies in the devDependencies of a given leaf package.json, and the topological order will be respected by lerna run.
> https://github.com/lerna/lerna/issues/2009#issuecomment-491971922

**Comment by develohpanda** [comment]
That seems logical, many of those weren't even in flow before so didn't need any build which might explain why it JustWorked™️ before

**Comment by develohpanda** [comment]
@dimitropoulos that link actually states that any `peerDependencies` should be specified as _devDependencies_. In `insomnia-app`, most of these are actually specified as `dependencies`; I don't know if that will have an issue in future but we can cross that bridge if we get to it

**Comment by develohpanda** [comment]
I removed the `peerDependencies` commit for now, I think removing the `--parallel` had already fixed it, and if it doesn't we can revisit this.

Looking at the lerna docs, the `--parallel` option explicitly ignores toplogical order

**Review by develohpanda — APPROVED** [review]

**Pull request merged**
