### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by hezhizhen**
Fixed some typos. It also corrected `options.validUntil` from `optons.validUntil`.

### CODE REVIEW

**Comment by jackkav** [comment]
Great job thanks!
did you use a tool you could share? 
Or was it manual with a spelling editor plugin?

**Comment by hezhizhen** [comment]
> Great job thanks! did you use a tool you could share? Or was it manual with a spelling editor plugin?

I use https://github.com/crate-ci/typos to quickly find some typos and use JetBrains IDEs to find more typos. Actually I don't fix them all, because I'm not familiar with JS/TS/TSX and I'm not sure if the change will break something.

If you like it, I can add https://github.com/crate-ci/typos to your existing CI as a spell checker. See https://github.com/tensorchord/envd/pull/1493 as an example.

**Comment by hezhizhen** [comment]
@jackkav WDYT?

**Review by filfreire — APPROVED** [review]

**Comment by jackkav** [comment]
@hezhizhen Thanks for the tip it does seems like a cool thing to automate, but we need to decide the right place to run  the tool. I think this PR is ready to merge.

**Review by jackkav — APPROVED** [review]

**Comment by hezhizhen** [comment]
> @hezhizhen Thanks for the tip it does seems like a cool thing to automate, but we need to decide the right place to run the tool. I think this PR is ready to merge.

Sure.

**Comment by filfreire** [comment]
@hezhizhen you can claim a free tshirt for this PR contribution - find more at https://konghq.com/community/open-source-contribution

**Pull request merged**
