### PR TITLE
disable sentry in dev

### PR DESCRIPTION
**Pull request by jackkav**
https://github.com/getsentry/sentry-javascript/issues/4509

### CODE REVIEW

**Review by filfreire — APPROVED** [review]

**Review by dimitropoulos — CHANGES_REQUESTED** [review]
https://github.com/Kong/insomnia/pull/4817#pullrequestreview-987954916

**Comment by dimitropoulos** [comment]
cc: @johnwchadwick but my understanding is that since we can filter by environment the canonical way to do this in sentry is what we're doing.  Disabling it in dev means we can't test sentry in dev, which would be problematic.

What's the motivation for this PR?

**Comment by johnwchadwick** [comment]
I would also like to know the motivation for the PR. I thought it would be quite useful to have Sentry in dev, as long as it didn't cause too much traffic or anything like that. WDYT?

(As far as practical use cases go, one particularly nice use case is symbolizing segfaults. If there are privacy concerns, of course, people can opt-out through the normal analytics option.)

**Comment by jackkav** [comment]
My motivation was a preference to opt-in to development error logging to remote rather than opt-out. Happy to close though since our segment analytics appear to be also logging to remote in development. To me it doesn't seem like reasonable default to have a remote log of unopted-out developers debugging experience all the time. It's a preference. I'll go and disable analytics for myself.

**Comment by johnwchadwick** [comment]
I see. Yes, I just upheld the former status quo; I would not mind having an option specific to error reporting, but I didn't want to open a rabbithole for how to handle it for existing and new users. (I definitely think that users would be annoyed if they had to go through a ton of different modals, especially users who don't want to send anything to a remote server at all.) Maybe it's worth discussing further at some point.

**Comment by dimitropoulos** [comment]
what about if we set analytics to false by default but only for local development?

**Pull request closed without merging**
