### PR TITLE
Upgrade Electron to 9.3.5

### LINKED ISSUE #2835: Broken rounded corners in Big Sur
**Describe the bug**
Broken rounded corners in Big Sur

**To Reproduce**
1. Run `brew install --cask insomnia`

**Expected behavior**
Rounded corners following Big Sur's UI pattern.

**Screenshots**
image

**Desktop:**
 - OS: Big Sur 11.0.1 (20B29)
 - Installation Method: Homebrew
 - App Version v2020.4.2

### LINKED ISSUE #2860: [Bug] Interface is slow on MacOS Big Sur
After update to the last Mac OS Big Sur interface became slow, application startup is slow and resizing (and even minimizing the window!) is freezing.

### PR DESCRIPTION
**Pull request by yunyu**
Closes #2860, Closes #2835: https://github.com/electron/electron/pull/24702

Partially solves #2964 (it will now run under Rosetta 2): https://github.com/electron/electron/pull/26572

### CODE REVIEW

**Comment by develohpanda** [comment]
Very cool, thanks for the PR! This has been on our roadmap in order to better support Big Sur. 

Windows/Ubuntu CI failed due to bootstrapping, so I've re-run it in case there was an issue with NPM.

**Comment by yunyu** [comment]
@develohpanda Unfortunately, I don't have access to a windows machine or graphical linux box at the moment. Would you be happen to be able to fix the PR?

For windows, it looks like python 3 is running on the CI but the scripts included use python 2.
For linux, it looks like the curl-config command is missing.

**Comment by develohpanda** [comment]
No stress, I was expecting issues with node-libcurl while upgrading, I already had to pin the version during the last release 😂 will take a deeper look when I get a chance to!

**Comment by yunyu** [comment]
@develohpanda The linux build passes when downgrading Electron to 9.3.5 and upgrading node-libcurl (as there are precompiled binaries). The windows build should pass, except it looks like the github archive server is returning a 503 (it may pass later).

Luckily, this is still a recent enough release to support running on Rosetta 2.

**Comment by yunyu** [comment]
@develohpanda looks like it went through this time!

**Comment by develohpanda** [comment]
Awesome! 🌞 I think this will require a degree of QA, but I'll raise it with the team and see where we can fit it in, so I won't merge it immediately but we _will_ get to it! 🤗

**Comment by koldoon** [comment]
This will bring significant improvement for the product, can someone resolve conflicts?

**Comment by dimitropoulos** [comment]
while I can't say for sure, I think after yesterday's release this particular change will start to bubble up in priority fairly quickly.  it's definitely on the radar!  I'd love it! haha

**Review by develohpanda — COMMENTED** [review]
Changes look good!

I'm seeing the following error when running locally for development, having cleared all node modules and bootstrapped again. Very strange, but it's a good sign that the smoke tests have passed (which make network requests as well)! This issue might be isolated to my dev environment,  will investigate further.

image

**Comment by DMarby** [comment]
@develohpanda I'm getting the same error, it seems like the newer precompiled `node-libcurl` build that is pulled in alongside the newer electron doesn't correctly statically link to zstd, so we might need to get that resolved upstream before we can proceed with this electron upgrade:  https://github.com/JCMais/node-libcurl/issues/274.

image

**Review by develohpanda — APPROVED** [review]
Looks to be running now after node-libcurl upgrade 👍🏽

**Review by DMarby — APPROVED** [review]
:shipit:

**Review by dimitropoulos — APPROVED** [review]
functionally tested on (k)ubuntu: looks good!!!11!1!

**Review by sonicyeti — APPROVED** [review]

**Pull request merged**
