### PR TITLE
Add text/plain body type

### LINKED ISSUE #3484: Content type text/other is broken
**Describe the bug**
Switching Content Type "text/othe"r on Insomnia POST requests has no effect on Content Header.

**To Reproduce**
* Create a POST Request in Insomnia and select the Content Type (e.g. text/edn)
* Switch the Content Type to text/other
* Submit your request
* check Request timeline
* Content Type stays "text/edn"

grafik

**Expected behavior**
My expectation is that when i explicitely select the content header, there is a modification on submitted content header.
Option 1) clear the content header field in request
Option 2) because the option "other" is grouped under "text": set text/plain as Content-Header field
grafik

I prefer Option 2

**Screenshots**
see above

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Installation Method: Traditional Autoupdate
 - App Version 2021.03.0

**Additional context**
nothing

Thanks in advance

### PR DESCRIPTION
**Pull request by theozordako**
This fixes issue with content-type dropdown for text/plain in header of requests and leaves content type "other" untouched.

### CODE REVIEW

**Review by theozordako — COMMENTED** [review]
Import of new Content Type Added

**Review by theozordako — COMMENTED** [review]
Works.
grafik

**Review by develohpanda — APPROVED** [review]
I don't think this PR closes what is described in #3484 so have unlinked this PR from the issue. I have asked for some feedback about it, and I'll chime in on the issue once we know how we want to fix it!

That said, this PR looks good to me as just introducing a plain text body type!

image

**Comment by theozordako** [comment]
@wdawson @dimitropoulos Could you please review this pull-request? Just 4 lines of code ;) Thx.

**Review by wdawson — APPROVED** [review]
This looks good to me as well. Thanks for the quick add @theozordako ⛵

**Pull request merged**
