### PR TITLE
Add Bearer Authorization Support

### PR DESCRIPTION
**Pull request by mai7star**
I wrote a patch to add Bearer Authorization Scheme (RFC6750) Support.

### CODE REVIEW

**Comment by gschier** [comment]
Thanks @mai7star. This looks great, but can you provide a screenshot since it touches UI?

**Comment by mai7star** [comment]
@gschier This is the screenshot.

**Comment by gschier** [comment]
Thanks!

**Comment by gschier** [comment]
@mai7star just thought I'd let you know that was able to simplify your component. You can take a look at the change here if you're curious. https://github.com/getinsomnia/insomnia/commit/53ff1a264eed77f0fc6dd701f8de9b8e94d4b846#diff-e61adbdedd4ecf5d81f825f7e6774af0

**Pull request merged**
