### PR TITLE
feat: set up sandbox for script execution [INS-3378]

### PR DESCRIPTION
**Pull request by ihexxa**
Changes:
This change basically sets up a sandbox which is an isolated environment for executing scripts, it contains following changes:

- modified building config for building index.js for the sandbox
  - packages/insomnia/esbuild.main.ts
  - packages/insomnia/vite.config.ts
- introduced sandbox renderer
  - packages/insomnia/src/preload.ts
  - packages/insomnia/src/renderers/hidden-browser-window/index.ts
  - packages/insomnia/src/renderers/hidden-browser-window/inso-object.ts
  - packages/insomnia/src/renderers/hidden-browser-window/index.html
- sandbox creating (in the main.js)
  - packages/insomnia/src/main/window-utils.ts
  - packages/insomnia/src/main/ipc/hidden-browser-window.ts
- sandbox controlling (starting, closing)
  - packages/insomnia/src/ui/window-message-handlers.ts
  - packages/insomnia/src/global.d.ts
  - packages/insomnia/src/ui/index.tsx
- misc (tests, debugging)
  - packages/insomnia-smoke-test/tests/smoke/pre-request-script.test.ts. 
  - packages/insomnia-smoke-test/tests/smoke/oauth-gitlab.test.ts
  - packages/insomnia-smoke-test/tests/smoke/git-sync.test.ts

### CODE REVIEW

**Comment by jackkav** [comment]
We should document the intended lifetime of the hidden browser window, eg. app start->app close or per function call, or whatever.

**Comment by ihexxa** [comment]
@jackkav It sounds reasonable, I've updated its design and workflow in the doc, please have a look.

**Comment by ihexxa** [comment]
Will create a naive version for this.

**Comment by jackkav** [comment]
closing as a spike, merged in #7063 #7065

**Pull request closed without merging**
