### PR TITLE
removes right pane swagger preview

### PR DESCRIPTION
**Pull request by jackkav**
changelog(Improvements): Removed the Swagger preview from Design to provide a cleaner editing experience and in order to support OAS v3.1

As discussed with @mheap the right hand swagger ui pane crowds the editing experience and is of dubious value. 
This change is also required in order to support OAS 3.1
Future work could include an export to request collection button and some way to send a request from the design view.
Question to reviewers: Is there anything we can do in this or a follow up PR that would help with removing this?

Previously:

image

Change:

image

### CODE REVIEW

**Comment by mheap** [comment]
To be clear, *I* don't find it useful, but I imagine some consumers rely on it. I'd put this behind a toggle initially in case people need it

**Comment by filfreire** [comment]
@jackkav I think this would fit with a follow-up PR to add a button to "Re-Generate" the requests on Debug tab from the spec.  That would help us solve INS-2148

EDIT: @gatzjames PR #5458 addresses the concern  - so nothing more to add to this 👍

**Review by filfreire — APPROVED** [review]
John Wick approves this PR

**Review by gatzjames — APPROVED** [review]
+💯
The debug view can handle most of the use-cases of the swagger-ui.
Also having the generate requests button closes the UX loop.

**Comment by jlsajfj** [comment]
> To be clear, _I_ don't find it useful, but I imagine some consumers rely on it. I'd put this behind a toggle initially in case people need it

bump on this, maybe a toggle in the drop downs? I relied on this feature quite a bit to expedite my process, however I'm quite green with OpenAI which might be why I relied on it.

**Comment by nihadguluzade** [comment]
Maybe hide it for OpenAPI 3.1+ versions instead of removing it completely? It was a useful feature for me

**Comment by jackkav** [comment]
A description of how it was useful would go long way in helping us incorporate your use case.

**Comment by desilvai-target** [comment]
My team used the preview pane heavily.  I have green developers that don't yet know how to read a swagger spec as YAML.  They will get there eventually, but that is just one more thing they need to learn (all at the same time).  We relied on the preview pane to go over the work they would do and they would reference it from the spec I'd provide them.  They checked their work against the spec.  

Additionally, the preview pane prevented us from having to jump around the doc (we have a ton of structures that are referenced within the spec and having to jump back and forth is difficult).  Perhaps we don't leverage the side pane enough, but it is one thing to follow the references around (especially for embedded object definitions) and it is quite another to see it rendered together.  We have caught a number of mistakes by reading over the rendered preview.

Leaving us without a means of regenerating the preview from the document is a huge hurdle for us.  What are the plans to replace the preview feature with some sort of render operation?  Will that be coming soon?

**Comment by andrevtg** [comment]
It was awesome for most newbies. It was the best WYSIWYG experience btw...

**Comment by CSnowss** [comment]
I was quite surprised that this was removed as well.  In fact, I opened a support ticket as I thought insomnia was broken with this the update.  It was the main feature I used insomnia for.  

OpenAPI specifications provide a an easily human readable form of documentation for users of your api when rendered in swagger-ui such as in Kong Developer Portal.  Seeing how your API will be rendered in the swagger preview gives an idea of what it will look like when uploaded to the portal.  

Ideally this feature would be added back with a toggle to disable it.  If the rendering engine is not capable of supporting OAS3.1 yet, maybe disable the toggle only for those specs.

**Comment by yellowberryHN** [comment]
As a temporary solution, you can revert to [2022.6.0](https://github.com/Kong/insomnia/releases/tag/core%402022.6.0), which still has the feature in question. Rather strange that they opted to remove it entirely instead of disabling it for unsupported files.

**Comment by pexa-slee** [comment]
Any chance we can revert this change? I have non tecchy folk that design OAS' complain to me that they cannot preview what the doc looks like. If not, I will have to ask them to switch to stoplight instead. Cheers.

**Pull request merged**
