### PR TITLE
feat(tests): support json schema validation

### PR DESCRIPTION
**Pull request by kobenguyent**
Closes https://github.com/Kong/insomnia/discussions/6507

Screenshot 2023-09-19 at 13 55 48
Screenshot 2023-09-19 at 13 56 00

changelog(Improvements): Add support for json schema in unit tests

Closes INS-3325

### CODE REVIEW

**Comment by mirket999** [comment]
As I experienced, isn`t it supported to validate schema until your changes are merged?

**Comment by kobenguyent** [comment]
> As I experienced, isn`t it supported to validate schema until your changes are merged?

indeed @mirket999

**Comment by mirket999** [comment]
> > As I experienced, isn`t it supported to validate schema until your changes are merged?
> 
> indeed @mirket999
It is one of the core things in API testing. Hopefully your changes will be deployed soon and solve the issue.

**Review by gatzjames — APPROVED** [review]
Thanks for the contribution! 🚀
Updated a test to the inso smoke tests to make sure it works there too!

**Comment by kobenguyent** [comment]
> Thanks for the contribution! 🚀 Updated a test to the inso smoke tests to make sure it works there too!

Thanks @gatzjames for the review!

**Review by filfreire — APPROVED** [review]
🚀

**Pull request merged**
