### PR TITLE
More Plugin Hooks

### PR DESCRIPTION
**Pull request by gschier**
## What

Related to #51 

This adds a couple more plugin hooks to the app. There will be more coming later, but this should be a good start.

### Plugin Context API

A plugin context is passed to every plugin function when ran.

- [x] `context.request.*` (only accessible during request hooks)
  - [x] `getMethod()`
  - [x] `getUrl()`
  - [x] `getName()`
  - [x] `getId()`
  - [x] `addHeader(name: string, value: string)`
  - [x] `setHeader(name: string, value: string)`
  - [x] `removeHeader(name: string)`
  - [x] `hasHeader(name: string)`
  - [x] `getHeader(name: string) -> string`
  - [x] `setCookie(name: string)`
  - [ ] ~~`getEnvironmentVariable(path: string) -> any`~~ removed due to security/privacy
- [x] `context.response.*` (only accessible during response hooks)
  - [x] `getStatusCode() -> string`
  - [x] `getStatusMessage() -> string`
  - [x] `getBody() -> Buffer`
  - [x] `getSize() -> number`
- [x] `context.app.*` (always accessible)
  - [x] `alert(message: string)`

### Other Things

- [x] More Flow types in various places
- [x] Add setting to specify extra plugin folders to look in
- [x] Refactor to make plugin loading async
- [x] Add ability to refresh template tag editor preview
- [x] Refactor tests to move all `beforeEach` into one place

### CODE REVIEW

**Comment by Lube** [comment]
should app context provide an API to change env variables? Im needing that and cannot find a way to do that

**Comment by Misiu** [comment]
@gschier what about accessing full request body? Is it supported? I need to access it to calculate hash and set custom header.
I saw plugin that can access request body: https://github.com/sujrd/insomnia-plugin-hmac-auth/blob/master/src/hmac-hook.js#L26 using `request.getBodyText()`, but I need to access request.body as bytes.
See my usecase: https://stackoverflow.com/questions/49509612/postman-access-full-request-body-to-calculate-hash-in-pre-request-script

When I do `Multipart Form` request I need to read RAW request and calculate hash from it.

I'm very new to Insomnia, but I'm very amazed with it's functionality and flexibility of plugins.
Having ability to access RAW request would allow me to move from Postman to Insomnia.

**Comment by gschier** [comment]
@Misiu that's something I plan to add. It's a bit tricky because of the way things are set up now, which is why it hasn't been implemented yet.

**Comment by Misiu** [comment]
Hi @gschier any news about this? Currently I'm using custom C# app to test my API, but I'd like to move to Insomnia.
One thing that blocks me is ability to access RAW request and calculate hash.
I'm not sure if [this issue](https://github.com/getinsomnia/insomnia/issues/870) is related, but ideally HMAC should be added to options in Auth list.

I can try helping with it if I'll be able to calculate hash of full raw request..

**Comment by gschier** [comment]
Thanks for reminding me about this @Misiu. I've been wanting to get to this but it's going to require a bit of thinking to implement it correctly (hence the delay). I just made an issue for exposing the body specifically if you want to follow it or submit some feedback.

https://github.com/getinsomnia/insomnia/issues/992

**Pull request merged**
