### PR TITLE
Fixes #682: Support postman import schema v2.1.0

### LINKED ISSUE #682: [Feature Request] Support Import from Postman v2.1.0
- Insomnia Version: 5.12.4
- Operating System: macOS Sierra 10.12.6

## Details

I'd like to be able to export from latest Postman and import into Insomnia. There is a new v2.1.0 schema for postman collections available: https://schema.getpostman.com/

Looking around the code, someone probably has to diff for changes between v2.0.0 and v2.1.0, and add another branch to https://github.com/getinsomnia/insomnia/blob/develop/packages/insomnia-importers/src/importers/postman.js#L17

### PR DESCRIPTION
**Pull request by coderjoe**
This PR implements support for postman import schema v2.1.0 to the same extent that v2.0.0 was supported. Most notably this means that authentication parameters still are not imported for either version.

Closes #682

### CODE REVIEW

**Comment by coderjoe** [comment]
If this PR is considered OK I'd like to take a stab at adding support for importing some of the authentication parameters from Postman imports (both v2.0 and v2.1)

**Comment by gschier** [comment]
Oh wow, it looks like not much changed between 2.0 and 2.1. Perhaps things were changed/added that we don't support yet? Either way, this looks awesome, thanks for doing it! 💯

**Comment by gschier** [comment]
And yes, please go ahead and extend support where needed. I'm sure A LOT of people will appreciate the improvements

**Comment by coderjoe** [comment]
@gschier per your suggestion I've added support for all of the auth methods that I use both personally and at work. It isn't all of them, but it is most. You'll find them in PR #1244 .

Thanks for your help!

**Pull request merged**
