### PR TITLE
perf: Improve performance with large OpenAPI files [INS-3724]

### LINKED ISSUE #4653: Insomnia has become unresponsive open api specs 3
### Expected Behavior

Load Specs design document properly.

### Actual Behavior

Showing an error of Insomnia has become unresponsive, and there is no way i can remove this import from my workspace. 

### Reproduction Steps

1. Goto Settings > Data > Import data > From File
2. Open API spec with some error in specification and it has to be large. 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 2022.2.1
Release date: 22/03/2022
OS: Windows_NT x64 10.0.19043
Electron: 17.1.0
Node: 16.13.0
V8: 9.8.177.11-electron.0
Architecture: x64

### Insomnia Version

2022.2.1

### What operating system are you using?

Windows

### Operating System Version

Windows_NT x64 10.0.19043

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

_No response_

### PR DESCRIPTION
**Pull request by CurryYangxx**
Close #4653 #4241 

**This PR is to solve the problem of slow response to open and edit spec files**
The main reason is `spectral.run` spend too much time and block the main process

**Changes：**

- [x] remove the spectral lint logic in the loader
- [x] move spectral from main process to worker thread
    - [x] add workerpool package to admin the worker
    - [x] modify the spectralRun IPC
- [x] wrap code-editor with memo to reduce rerender

### CODE REVIEW

**Comment by jackkav** [comment]
can you describe your reasoning for choosing workerpool over alternative approaches please, eg utilityprocess

**Comment by CurryYangxx** [comment]
> can you describe your reasoning for choosing workerpool over alternative approaches please, eg utilityprocess

I read the electron documentation about the [performance best practices](https://www.electronjs.org/docs/latest/tutorial/performance#3-blocking-the-main-process), it says we can use worker threads for long running CPU-heavy tasks. And I think the spectral.run is the same situation.I found workerpool is convenient to admin workers ,so I choose this package.

**Comment by jackkav** [comment]
we have code mirror linter running in the renderer right now, perhaps we can run spectral in a similar way? worth exploring?

**Comment by CurryYangxx** [comment]
We solve this issue in another appraoch in #7374. This PR is reserved for future use of the node worker treads

**Pull request closed without merging**
