### PR TITLE
Allow optional specification of Origin header for Auth Code flow + PKCE

### LINKED ISSUE #794: [Bug] OAuth 2 Authorization Code issue with Insomnia newer version
- Insomnia Version: v5.14.9
- Operating System: Windows 10

## Details

Hi
I am having issue with OAuth 2.
Now looks like only implicit grant type that is working but never with authorization code. I used it before I upgrade (few months ago) and the Refresh token was always retrieved properly on Azure AD

Here are some debug info:

> [oauth2] Ignoring URL "https://login.microsoftonline.com/dcfabrik.onmicrosoft.com/oauth2/authorize…DcyNGQwMjk1IiwiVElEIjoiOTI1Y2QxMmEtNjI4NC00YmFjLWIxNzYtMzUwNDI1NzFmMTkzIn0". Didn't match /https:\/\/insomnia\.rest\/.*(code=)/i
> 
> [oauth2] Matched success redirect to "https://insomnia.rest/?code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjE…6tflXkCUuOxDDK6_AVOP0ougLXYfZc4mSAJu3Z_-vqoXAeDWKfA._d4-L5Z1lDiE4F8gxVUvzQ" with /https:\/\/insomnia\.rest\/.*(code=)/i
> 
> [oauth2] Detected redirect https://insomnia.rest/?code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjE…6tflXkCUuOxDDK6_AVOP0ougLXYfZc4mSAJu3Z_-vqoXAeDWKfA._d4-L5Z1lDiE4F8gxVUvzQ

And this end up on token failure on Insomnia as Bad Request:

> [oauth2] Failed to fetch token url=https://login.microsoftonline.com/dcfabrik.onmicrosoft.com/oauth2/v2.0/token?p=b2c_1_signin status=400

It was working in oldets version...

### PR DESCRIPTION
**Pull request by p-m-j**
Closes #794

@wdawson this is slightly lazier than the approach discussed in https://github.com/Kong/insomnia/discussions/3572 but it feels reasonable to stuff Origin header into the advanced options section.

image

### CODE REVIEW

**Comment by wdawson** [comment]
Thanks, @rustybox this certainly works for now. At some point, it may make sense to come back and revisit for a more generic solution but I don't want to let perfect be the enemy of good here. I'll let others do the actual code review as well but thanks for your contribution! 🙌

**Comment by p-m-j** [comment]
Pushed linting fixes and removed some indentation my editor decided to add.

Even when custom headers are in I wonder if origin deserves a place in Advanced Options for the signposting, I imagine custom headers would be used more for X-Foo style headers.

**Review by develohpanda — APPROVED** [review]
Looks to be working well in the app, haven't tested with a valid endpoint. Thank you for the PR!

image

Waiting on one more eng review before merging 😄

**Review by gatzjames — APPROVED** [review]
Just tested it and it works great! 👍

**Comment by p-m-j** [comment]
rebased on develop & resolved conflicts

**Comment by develohpanda** [comment]
> rebased on develop & resolved conflicts

Thank you!

**Pull request merged**
