### PR TITLE
Add ability to save results of JSONPath filter to a file

### LINKED ISSUE #3172: Feature Request: Save results of JSONpath filter to a JSON file
The existing "Save Raw Response" is great, but what if I need to save the results of a JSONPath filter? I assume it would be useful to create a "Save Filtered Response" for this purpose. Another possibility is to modify the existing "Save Response" such that when a result is being filtered with JSONPath, then it will save the filtered version rather than the full result. 

Here's a Photoshopped mockup.
image

I would love to see opinions or discussion here.

### PR DESCRIPTION
**Pull request by akshaymattoo**
ezgif com-gif-maker (1)

Closes #3172

### CODE REVIEW

**Comment by dimitropoulos** [comment]
this is really cool!  @nijikokun what do you think on the language ("Save Filtered Response")?

**Comment by nijikokun** [comment]
> "Save Filtered Response"

Sounds good to me! I can't think of anything better that is as concise and direct at the moment.

**Comment by nsitu** [comment]
I'm not sure what the process is here, but I'm just commenting to say I would love to see this feature implemented.

**Comment by jackkav** [comment]
Closed as stale.

**Comment by ericpyle** [comment]
Any plans to reopen this?

**Pull request closed without merging**
