### PR TITLE
Always generate base environment id when importing

### LINKED ISSUE #4178: Hidden and uneditable environments on Manage Environments after importing JSON
### Is there an existing issue for this?

- [x]  I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Insomnia Version
2021.6.0

### What operating system are you using?
macOS

### Operating System Version
macOS Big Sur 11.6

### Installation method
download

### Last Known Working Insomnia version
2021.5.3

### Expected Behavior
The environment vIew (Manage Environments) should list all existing environments with their already set variables

### Actual Behavior
Already existing environments of older Insomnia versions are not listed within the environment view, even they are available for the dropdown (to switch environments), but the variables are not available within calls.

### Reproduction Steps
Create a Request Collection with an environment in Insomnia. Export the Request Collection (Insomnia V4 JSON). Delete the project and create a new Request Collection. Do an Import of the JSON export. The environments are still visible within the switch for environments, but not if you want to edit them within Manage Environments - even they are fully part of the JSON export.

### Additional Information
/

### PR DESCRIPTION
**Pull request by vincendep**
changelog(Fixes): Fixed an issue that caused dangling base environments when importing an Insomnia collection

This pull request ensures the "regeneration" of the base environment id when importing a collection.
Preventing the creation of an additional base environment,  will be possible to import into an existing collection (modifying the export file) without losing all the exported environments .

Closes #4178

### CODE REVIEW

**Comment by filfreire** [comment]
Possibly linked with https://github.com/Kong/insomnia/issues/3112

**Comment by vincendep** [comment]
Hi @dimitropoulos and @filfreire . I just saw the stream and I'll try to clarify. 
I was trying to replace the base environment _id property with the placeholder (and therefore also the parentId property of subenvironments since they have a parent-child relation) thus, in case of manually editing the workspaceId in the export file, the right id would be picked during the import phase.

Said that, this code is buggy and so the draft status. Also I don't know if actually make sense to support such a usecase of manually editing the export file, given that now is also present a functionality to import into an existing workspace.

**Review by filfreire — APPROVED** [review]

**Comment by filfreire** [comment]
heads up @Kong/team-insomnia I added a unit test that reproduced the previous faulty behavior. The edge case was such that when reimporting we would end up with dangling environments which the user could no longer interact with.

**Review by jackkav — APPROVED** [review]

**Comment by filfreire** [comment]
@vincendep thanks for contributing this and sorry for the long wait on the merge. In the meantime I added tests 👍 

This will go in the next release.

**Comment by vincendep** [comment]
Hi @filfreire. No problem, happy to contribute. 😁

**Pull request merged**
