### PR TITLE
Add getParameters to Request Hook API

### PR DESCRIPTION
**Pull request by amree**
This will add `getParameters` so that we can access the parameters sent. It's actually pretty similar to https://github.com/getinsomnia/insomnia/pull/731 but with smaller scope (and with test). I don't mind if the former PR got merged first as I really need this functionality 😆

### CODE REVIEW

**Comment by floatinglacier** [comment]
This is exactly what I'm looking for.  Thank you @amree!

**Comment by floatinglacier** [comment]
@gschier is there any chance to release this soon? Thanks

**Comment by gschier** [comment]
Getting to it soon. It'll be in the next release for sure

**Comment by gschier** [comment]
Added a fully-implemented solution in https://github.com/getinsomnia/insomnia/commit/dc0695de23f3c2b3a1d9086d1c972ca03313fdd6

**Pull request closed without merging**
