### PR TITLE
adds "Made with :heart: by Kong" to footer of dashboard

### PR DESCRIPTION
**Pull request by dimitropoulos**
closes INS-1290

This PR removes the existing footer and replaces it with one that reads "Made with :heart: by Kong".

| BEFORE | AFTER |
| - | - |
| Screenshot_20220216_151620 | Screenshot_20220216_151424 |
| Screenshot_20220216_151640 | Screenshot_20220216_151452 |
| Screenshot_20220216_151659 | Screenshot_20220216_151512 |

 Hoverstate looks like this:
Screenshot_20220214_181120

### CODE REVIEW

**Review by wdawson — CHANGES_REQUESTED** [review]
Let's get rid of the document count and footer divider while we're at it.

**Comment by dimitropoulos** [comment]
@wdawson all updated now: please take another look

**Review by wdawson — APPROVED** [review]
⛵ Looks great to me!

**Review by jackkav — APPROVED** [review]
Nicely done, Goed zo!

**Pull request merged**
