### PR TITLE
Release branch for 2020.5

### PR DESCRIPTION
**Pull request by develohpanda**

### CODE REVIEW

**Comment by DMarby** [comment]
@develohpanda Do we need to update/publish any NPM packages for this release btw?

**Comment by develohpanda** [comment]
Good question, I'll double check to see what might be impacted

**Comment by DMarby** [comment]
@develohpanda Based on the following output from `lerna changed`
image
and a quick check, I think `openapi-2-kong`, `insomnia-inso` and the plugins needs a release due to this change: https://github.com/Kong/insomnia/pull/2709

**Comment by develohpanda** [comment]
Note, all the build failures are due to Netlify. The CI actions are successful, to be fixed by #2874.

**Pull request merged**
