### PR TITLE
[Documentation] Change issues link on README

### PR DESCRIPTION
**Pull request by xeptore**
hi.
i think it should refer to `issues` page or it might be `](../../issues/new` in order to _open a new issue_

### CODE REVIEW

**Comment by gschier** [comment]
Where is the link you're referring to?

**Comment by gschier** [comment]
A relative link seems less reliable because it depends which page you're viewing the rendered markdown from.

Example: If I'm viewing the README from here, the relative link will 404
https://github.com/getinsomnia/insomnia/blob/34894563a859b31b73926207ee518e384a72c6f5/README.md

What is the reason you don't want it to be absolute?

**Comment by gschier** [comment]
My first thought was to make it the full URL `https://github.com/getinsomnia/insomnia` but I wanted it to still work if the repo name changed. Perhaps the full URL would be the most reliable though.

**Comment by xeptore** [comment]
yes, youre right. but i thought because README.md file is always at the root level of project files it would be easier to fix where it refers with a `../` instead of making it an absolute link. but as you said its not a good idea when reading that file from commits or somewhere else, so now i think an absolute link is a better idea in total.

**Pull request closed without merging**
