### PR TITLE
🚀 2021.4.0 Beta - the one with TypeScript 

### PR DESCRIPTION
**Pull request by develohpanda**
https://github.com/Kong/insomnia/compare/core@2021.3.0...2021.4.0-beta

Note: all packages received a pre-minor bump (instead of pre-patch) for the beta and upcoming stable

See comments below, fixes INS-706

### CODE REVIEW

**Review by reynolek — APPROVED** [review]
excited

**Review by DMarby — APPROVED** [review]

**Comment by develohpanda** [comment]
It appears CI is failing on smoke tests because it cannot install `insomnia-importers` because `insomnia-importers@2.3.0-beta.0` is bugged. 

image

In order to fix this we need to fix importers and release a beta.1, then re-build the release.

I will do so now in the following commits, 
 relates to INS-706

**Comment by develohpanda** [comment]
This is why smoke tests keep failing after publishing packages
image

**Comment by DMarby** [comment]
@develohpanda I'm not sure that we can pack `insomnia-plugin-kong-bundle` since we need to be able to read the `package.json` of it, currently getting the following error when launching the app: 
image

**Comment by develohpanda** [comment]
Interesting 🤔 okay, what I'll do for the time being is disable smoke tests and remove it from packed deps to make sure everything is green; we know smoke tests run and the few cases in there we can check manually

**Pull request merged**
