### PR TITLE
postman import auth (from headers and/or auth object)

### LINKED ISSUE #4214: Importing a Postman collection loses almost all information
### Expected Behavior

The collection is imported fully and correctly.

### Actual Behavior

All URLs are empty, the body type is always set to “Other” instead of “No body” or “JSON” where appropriate:

image

image

No query parameters and authentication set to “No authentication” instead of Bearer (even though the Authorization header is added with `null` value):

image

### Reproduction Steps

1. Create a new collection (due to #4034).
2. Import from https://web.timingapp.com/docs/collection.json

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

_No response_

### Insomnia Version

2021.6.0

### What operating system are you using?

Other Linux

### Operating System Version

NixOS 21.05 (Okapi)

### Installation method

Nix

### Last Known Working Insomnia version

_No response_

### PR DESCRIPTION
**Pull request by sergiyladnych**
Closes #4214:
>-Body type set to "Other" (instead of extracting from the content-type header, for instance)
>-Auth not set (instead of extracting from the Authorization header, for instance)
>-URLs are empty
>-Query parameters don't import

One test input-output is added. It checks all implemented scenario.

changelog(Improvements): Adds ability to import postman authorization (from headers as well)

### CODE REVIEW

**Review by filfreire — APPROVED** [review]
@sergiyladnych thank you for this PR! 🎉 

Tested out locally, seems to be working ok ✅  

-Body type was set to JSON in all cases 
-Auth was set for the examples of `Bearer`, `AWS`, `Basic`, `Digest` and `Oauth 1` instead of showing up empty
-URLs are no long empty, and properly filled in
-And query parameters seemed to import ok 👍 

Example screenshot, left includes this PR changes, right is latest stable version:
Screenshot 2022-01-18 at 18 23 00 

There's some things we might need to look out for, but I would wait for review from one of my dev colleagues:
-  @sergiyladnych I would suggest you clean up a bit the fixture json files, for example, removing the requests that not used:

Screenshot 2022-01-18 at 18 32 23

- I noticed that in some cases there are missing fields. We are in the end limited by these kinds of edge case postman exports where postman does not include the `$.item[].request.auth` field. 

- @wdawson at one point it might be worth to deep-dive in one of our upcoming cycles in reviewing all sorts of imports/exports of postman and others deeply, I'm looking through some and find that many miss certain (optional) fields that might be of interest for us to check, example for oauth v1:
ouath1_example

**Review by dimitropoulos — CHANGES_REQUESTED** [review]
howdy @sergiyladnych!  @gatzjames and @filfreire and I looked at this today and decided we want to start moving forward with writing unit tests for these cases.  @gatzjames also had an idea for how we can sideline having to maintain the regexes at all - hopefully you'll see more on that soon.  I rebased and pushed (hopefully that's ok, if not let me know).

We're going to be looking into this soon, apologies on blocking the merge right away, but rest assured this is high on our radar.

**Comment by sergiyladnych** [comment]
@dimitropoulos Hello, 
I'm not sure that fully understood your latest comment. Is there some expectations from me to change smth? If yes could you elaborate on it.

**Comment by dimitropoulos** [comment]
hey @sergiyladnych.  so basically if you want to write more tests of the sort that were added in the last commit please feel free (it'll really speed things up), but if not, then members from the insomnia team are going to write them before we merge this PR.  from a functionality standpoint, too, @gatzjames had some ideas, so we may use the tests as a way to verify that switching from the current approach with regexes is compatible with his ideas for a different solution.

**Comment by dimitropoulos** [comment]
after quite a lot of work on this PR, it's time to draw a line somewhere.  what's here now provides significant value compared to what we had before and is now very thoroughly tested.

The only bit that remains is the url parsing of parameters https://github.com/Kong/insomnia/pull/4375/commits/cd5ae6cdc00143fe83c3d583ceda244498615f73 which we will need to handle separately.  We did try and dig into it but it's a bit of a rabbithole of complexity, as it turns out, whereas the auth translation stuff is more straightforward.  The reasons mostly have to do with parsing the URL vs the provided parameters and how to parse the URL to remove or add the parameters (since Insomnia and Postman have different behaviors in this respect).

**Review by filfreire — APPROVED** [review]
LGTM

**Review by dimitropoulos — APPROVED** [review]

**Pull request merged**
