### PR TITLE
[DRAFT] Add ability to build deb files on aarch64

### PR DESCRIPTION
**Pull request by jokaorgua**
This PR is a draft. 

I was able to add support of aarch64 containers for building the sources but I do not know how to add arm64 arch for building the packages.

Due to the logs of github actions it still builds x64 on aarch64

I need help with this.

I've checked out the insomnia on my ubuntu 20.04 ARM and ran it through ```npm run dev```. Everything seems to be ok. 
Maybe someone could advise better solution for building the arm version of snap or deb files? Would be great

### CODE REVIEW

**Comment by jokaorgua** [comment]
so the problem of building x86 on aarch64 was in fpm. it has a bug in version prior to 1.13 (https://github.com/jordansissel/fpm/pull/1775)

I've fixed the workflow to install the latest fpm from ubuntu's repo and use it for building

**Comment by jokaorgua** [comment]
I'm stuck with installing nvm in the container under aarch64. If anybody knows how to do that properly I will be really appreciated it. Or maybe somebody knows how to install specific version of nodejs without nvm?

**Comment by jackkav** [comment]
If I understand the intent of this PR correctly you would like to add arm64 architecture support to insomnia. Assuming that's the case it would be helpful to start locally and test it out before looking at github actions. Here's how this can be done using electron-builder. 
```sh
cd packages/insomnia
npm run build:app
BUILD_TARGETS=deb node_modules/.bin/electron-builder build --config electron-builder.config.js --arm64
```
```log
  • electron-builder  version=23.0.7 os=5.16.19-76051619-generic
overriding build targets to:  [ 'deb' ]
  • loaded configuration  file=/home/jack/git/insomnia/packages/insomnia/electron-builder.config.js
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=@getinsomnia/node-libcurl@2.3.5-1 platform=linux arch=arm64
  • packaging       platform=linux arch=arm64 electron=18.1.0 appOutDir=dist/linux-arm64-unpacked
  • building        target=deb arch=arm64 file=dist/Insomnia.Core-2022.4.0-beta.0.deb
```

**Comment by jokaorgua** [comment]
@jackkav I've already built arm64 deb on my local machine. Everything works correctly. But I can not make it building in github action. The main problem, currently, is to install needed version of node. I can not install nvm in arm64 virtual machine in github actions. And I do not know other way to install the exact version of node needed for building the Insomnia

**Comment by jackkav** [comment]
The node version is 16.3.2, you don't need nvm to build we just use .nvmrc to track this version in our tooling.

**Comment by jokaorgua** [comment]
@jackkav 
how to install the exact version of node without nvm ?
when I install it from repo for ubuntu it installs 16.5.0 and build fails

```
  > insomnia@1.0.0 preinstall
  > node ./scripts/check-version.js
  
  Incorrect node version installed ...
  
  Current node version -> 16.15.0
  Expected node version -> 16.13.2
```

**Comment by jokaorgua** [comment]
@jackkav I've found a way how to install exact version of node without npm

but now I have a problem which I can not solve by myself
```
Run `npm audit` for details.
  lerna notice cli v4.0.0
  lerna info ci enabled
  lerna info Bootstrapping 30 packages
  lerna info Installing external dependencies
  lerna ERR! npm ci exited 243 in 'insomnia-components'
  lerna ERR! npm ci stderr:
  glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
    errno: -13,
    code: 'EACCES',
    syscall: 'scandir',
    path: '/root/.npm/_logs'
  }
  npm ERR! code EACCES
  npm ERR! syscall lstat
  npm ERR! path /root/.npm/_cacache/content-v2/sha512/cb/5d/67184953215f824f766ff6ded52a5f90de14d0a13f5ad50cdece1865e91a76d6027f2154d6ed9df2f4459786e5010b64a19dff835f46a7b5e72903048ff3
  npm ERR! errno -13
  npm ERR! 
  npm ERR! Your cache folder contains root-owned files, due to a bug in
  npm ERR! previous versions of npm which has since been addressed.
  npm ERR! 
  npm ERR! To permanently fix this problem, please run:
  npm ERR!   sudo chown -R 1001:121 "/root/.npm"
  lerna ERR! npm ci exited 243 in 'insomnia-components'
  lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
```

I'm not a nodejs dev

**Comment by ParitoshBh** [comment]
@jokaorgua I don't have an exact solution to your issue but I did face a similar problem when compiling using a Dockerfile and I had to change user to root.

Also, glued together a script to compile for arm64, might give out a hint as to what's missing with your changes. Here it is - https://github.com/ParitoshBh/script-ions/tree/master/insomnia_arm64_deb

**Comment by jackkav** [comment]
Closed as stale.

**Pull request closed without merging**
