### PR TITLE
fix (style): set drag-sidebar z-index to 999

### LINKED ISSUE #4018: Document/Collection settings modal an interact with panels beneath it
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.2

### What operating system are you using?

Ubuntu

### Operating System Version

Kubuntu 21.04

### Installation method

apt

### Last Known Working Insomnia version

_No response_

### Expected Behavior

An open Document/Settings modal should not allow interactions with panels below it.

### Actual Behavior

You can resize the collection's sidebar with the modal open (but only on first load of the app!)

https://user-images.githubusercontent.com/15232461/132734903-ce7ff226-5d48-44b9-860f-dbdc073fcdba.mp4

### Reproduction Steps

1. open the app fresh
1. open a collection
1. open the collection settings
1. hover your mouse to a place where a panel exists below the modal

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by alk-mandrianarijaona**
modal `globalZIndex` starts at 1000 (https://github.com/Kong/insomnia/blob/d53ef39c9b76aefcfa71630078d838bb95eaad56/packages/insomnia-app/app/ui/components/base/modal.tsx#L11)
and anything with z-index >= 1000 will not be under overlay the first time a modal is open. 

Each time a modal is opened, the value of `globalZIndex` is incremented so this issue happens only one time (c.f https://github.com/Kong/insomnia/blob/d53ef39c9b76aefcfa71630078d838bb95eaad56/packages/insomnia-app/app/ui/components/base/modal.tsx#L107)

Closes #4018

### CODE REVIEW

**Comment by dimitropoulos** [comment]
Do you have any idea why this only happens when you first launch the app?

**Comment by alk-mandrianarijaona** [comment]
> Do you have any idea why this only happens when you first launch the app?

@dimitropoulos  Yes it is because we increment the value of `globalZIndex` each time we open a modal, so the second time, it's greater than 1000 and there is no issue anymore
c.f https://github.com/Kong/insomnia/blob/d53ef39c9b76aefcfa71630078d838bb95eaad56/packages/insomnia-app/app/ui/components/base/modal.tsx#L107

**Comment by alk-mandrianarijaona** [comment]
I updated the PR description to make it clearer

**Review by dimitropoulos — APPROVED** [review]
great find.  I added some documentation.  we'll have someone else from the team also take a look then this'll be ready to merge.  thanks!

**Review by develohpanda — APPROVED** [review]
LGTM! Thanks for the PR

**Pull request merged**
