### PR TITLE
fix: only change environment on fresh import

### LINKED ISSUE #2228: Insomnia Designer is always reset Environments to default
**Describe the bug**
I am using openapi 3.0.3.
When I clicking on Debug the "OpenApi env" is always created and auto selected. The Base Environment is loosing every custom variable.

**To Reproduce**
1. Create a new Blank document.
2. Edit the document with content:
```
openapi: "3.0.0"
info:
  title: API commands 
  description: This is the API documentation.
  version: 1.0.0
  
paths:
  /login:
    post:

```  
3. Click on the Debug button.
(OpenApi env is automatically created and selected)
4. Copy "OpenApi env" data and Create a new Sub Environment with these data.
5. Delete "OpenApi env".
6. Add a new key/value to Base Environment.
7. Select the new Sub Environment.t
8. Go back to Design.
9. Go again to Debug.

Then the "OpenApi env" is created and selected again, the new key/value variable is missing from Base Environment.

**Expected behavior**
Do not autocreate "OpenApi env" and save the state of Base Environment.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Installation Method: downloaded dmg from website
 - App Version: 2020.2.0

### PR DESCRIPTION
**Pull request by apisaint**
This change makes it so that when switching between debug and design tabs, it only selects the default environment *the first time*. Subsequent switches will test whether an active environment id has already been set and ignore.

I've updated the comments as well. Since there were no tests around this area, I did not add or edit any - and will not do so since I am not familiar with the tests infrastructure yet.

Impacts #2228
Impacts #2680

### CODE REVIEW

**Comment by nijikokun** [comment]
Welcome @apisaint!

**Comment by nijikokun** [comment]
Oops, clicked the wrong button by accident 😅 

Welcome @apisaint! Great work, I know we have gotten a few reports and requests for this so much appreciated. 🤗

**Comment by apisaint** [comment]
> Oops, clicked the wrong button by accident 😅

I've done it myself many times they are so close to each other!

> Welcome @apisaint! Great work, I know we have gotten a few reports and requests for this so much appreciated. 🤗

Thank you! ❤️ Hope to see it merged soon so others can benefit

**Review by dimitropoulos — CHANGES_REQUESTED** [review]
Thanks for the contribution! When I functionally tested this (against the steps listed in https://github.com/Kong/insomnia/issues/2228#issue-627996958) I still had properties removed in by Base Environment.  Is this intended to fix that (I'm assuming so because you said it closes that issue, but I wanted to be sure because otherwise we should track that other part separately).

**Review by dimitropoulos — COMMENTED** [review]
I can confirm, however, after functional testing that the "doesn't automatically change environments" part of this is fixed.

**Comment by apisaint** [comment]
> Thanks for the contribution! When I functionally tested this (against the steps listed in [#2228 (comment)](https://github.com/Kong/insomnia/issues/2228#issue-627996958)) I still had properties removed in by Base Environment. Is this intended to fix that (I'm assuming so because you said it closes that issue, but I wanted to be sure because otherwise we should track that other part separately).

It is not intended to fix that aspect, only switching. Can create another PR for that later.

**Review by develohpanda — APPROVED** [review]
LGTM, thanks for the PR - the parent issue will remain open but this is good as a partial fix for it.

**Pull request merged**
